name: "Label Validated PRs"
on:
  workflow_run:
    workflows: ["QIP File Validation"]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  label:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        id: pr
        run: |
          echo "Fetching PR number from workflow run"
          PR_NUMBER=$(echo '${{ github.event.workflow_run.pull_requests[0].number }}')
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
      
      - name: Add automerge label
        if: steps.pr.outputs.pr_number
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.pr.outputs.pr_number }}
          labels: automerge 